### ISSUE TITLE
Offer a secure created/login/logout service for users

### ISSUE THREAD

**Issue by BillyManGR** [tomescumihail93/cryptoment#10]
OAuth 2.0 hard to implement. Use Loopback's built-in models and methods instead. 
Steps/Challenges:
- Which (built-in) models/methods?
- Create DBs of the models in Cloudant
- Create data sources of the DBs in loopback
- Different content for registered
- Connect API with loopback so they communicate each other
- Handle unauthorized requests (401) Redirect with interceptors
- Create register/login/logout components(?) in Front End

**Comment by michelcojocaru** [comment]
Done.
